downloader/urls.py
from django.urls import path
from . import views

app_name = 'downloader'
urlpatterns = [
    path('', views.download, name='download'),
]

manager/urls.py
from django.urls import path
from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

app_name = 'manager'
urlpatterns = [
    path('files/', views.viewfiles, name='viewfiles'),
    path('register/', CreateView.as_view(template_name='manager/register.html', form_class=UserCreationForm, success_url='/' ), name='register'),
]

streamer/urls.py
from django.urls import path

from . import views

app_name = 'streamer'
urlpatterns = [
    path('', views.stream, name='stream'),
    path('<stream_id>/', views.receive, name='receive'),
]

uploader/urls.py
from django.urls import path

from . import views

app_name = 'uploader'
urlpatterns = [
    path('', views.upload, name='upload'),
]

urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', include('zerofile.uploader.urls')),
    path('s/', include('zerofile.streamer.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='uploader/index.html'), name='logout'),
    path('admin/', admin.site.urls),
    path('user/', include('zerofile.manager.urls')),
    path('accounts/profile/', RedirectView.as_view(url='/', permanent=True)),
    path('<file_id>/', include('zerofile.downloader.urls'))
]

import zerofile.autodelete

models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class File(models.Model):
    """ File class, contains file and metadata. User is null if anonymous """
    _id = models.CharField('File ID', max_length=15)
    name = models.CharField('File name', max_length=64)
    mime = models.CharField('Mimetype', max_length=64)
    upload_date = models.DateTimeField('Upload date')
    user = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING)
    expiry = models.DateTimeField('Expires at', default=timezone.datetime(year=2021,month=1,day=7))
    deleted = models.BooleanField('Deleted or expired', default=False)

    def __str__(self):
        return self.name

downloader/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseGone, Http404
from django.template import loader
from zerofile.models import File
from zerofile.settings import FILEDIR

def download(request, file_id):
    """ Serve file corresponding to the id """
    dbfile = get_object_or_404(File, _id=file_id)
    if dbfile.deleted:
        template = loader.get_template('downloader/deleted.html')
        return HttpResponseGone(template.render({'fileid': dbfile._id}, request=request))

    try:
        with open(FILEDIR + dbfile._id, "rb") as i:
            response = HttpResponse(i.read(), content_type=dbfile.mime)
            response['Content-Disposition'] = 'inline; filename=%s' % dbfile.name
            return response
    except:
        raise Http404("File not found")

manager/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from zerofile.models import File


def viewfiles(request):
    """ List a user's uploaded files """
    if request.user.is_authenticated:
        files = []
        for ufile in File.objects.filter(user=request.user):
            files.append({
                'name': ufile.name, 
                'date': ufile.upload_date, 
                'fid': ufile._id, 
                'deleted': ufile.deleted, 
                'expiry': ufile.expiry
            })
        template = loader.get_template('manager/files.html')
        return HttpResponse(template.render({'files': files}, request))
    return HttpResponseRedirect('/')

streamer/views.py
import string
import random
import magic
from datetime import timedelta
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.core.files.storage import default_storage
from django.template import loader
from zerofile.settings import FILEDIR

def stream(request):
    template = loader.get_template('streamer/index.html')
    return HttpResponse(template.render({ 'host': True }, request=request))

def receive(request, stream_id):
    template = loader.get_template('streamer/index.html')
    return HttpResponse(template.render({ 'host': False, 'stream_id': stream_id }, request=request))

uploader/views.py
import string
import random
import magic
from datetime import timedelta
from django.utils import timezone
from django.http import HttpResponse
from django.core.files.storage import default_storage
from django.template import loader
from zerofile.models import File
from zerofile.settings import FILEDIR

class ReqEx(Exception):
    pass

def upload(request):
    """ Processes form answer and stores it in db, returns upload page if answer is empty """
    if 'fileselect' in request.FILES and 'timeout' in request.POST:
        try:
            return upload_file(request)
        except ReqEx as e:
            return e.args[0]

    template = loader.get_template('uploader/index.html')
    return HttpResponse(template.render({}, request=request))

def upload_file(request):
    ufile = request.FILES['fileselect']
    validate_size(request, ufile)
    fileid = write_file(ufile)
    mime = get_mime(request, fileid)
    expiry = get_expiry(request, request.POST['timeout'])

    dbfile = File(_id=fileid, name=ufile.name,
                mime=mime,
                upload_date=timezone.now(),
                user=request.user if request.user.is_authenticated else None,
                expiry=expiry)
    dbfile.save()

    template = loader.get_template('uploader/ajax.html')
    return HttpResponse(template.render({'file_id': fileid, 'file_name': ufile.name},
                                        request=request))

def validate_size(request, file):
    if file.size > 50000000: # 50 Megabyte
        template = loader.get_template('uploader/index.html')
        raise ReqEx(HttpResponse(template.render({'file_toobig': True}, request=request)))

def write_file(file):
    fileid = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(7)])
    with default_storage.open(FILEDIR + fileid, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    return fileid

def get_mime(request, fileid):
    mime = magic.from_file(FILEDIR + fileid, mime=True)
    if mime in NOT_ALLOWED_MIMES and not request.user.is_authenticated:
        template = loader.get_template('uploader/not_allowed_mime.html')
        raise ReqEx(HttpResponse(template.render({}, request=request)))
    return mime

def get_expiry(request, time):
    try:
        delta = TIMEDELTAS[time]
        return timezone.now() + delta
    except:
        template = loader.get_template('uploader/invalid_timeout.html')
        raise ReqEx(HttpResponse(template.render({}, request=request)))

NOT_ALLOWED_MIMES = ["text/html", "text/x-php"]
TIMEDELTAS = {
    "minute": timedelta(minutes = 1),
    "hour": timedelta(hours = 1),
    "day": timedelta(days = 1),
    "week": timedelta(weeks = 1)
}

templates/base.html
{% load static %}
<html>

<head>
    <link rel="shortcut icon" href="{% static 'fav.png' %}" type="image/png" /> 
    {% block css %}<link rel="stylesheet" href="{% static 'css/index.css' %}">{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700,400" rel="stylesheet">
    <title>{% block title %}ZeroFile - Simple file host{% endblock %}</title>
</head>

<body ondrop="onDrop(event);" ondragover="event.preventDefault();">
    {% if request.user.is_authenticated %}
    <header>        
        {% block headerlink %}<a href="{% url 'manager:viewfiles' %}" class="link">My Files</a>{% endblock %} |
        <a href="/logout" class="link">Logout</a>
    </header>
    {% else %}
    <header>
        <a href="{% url 'manager:register' %}" class="link">Register</a> |
        <a href="/login" class="link">Login</a>
    </header>
    {% endif %}

    <h1 class="logo">ZeroFile</h1>

    {% block mode %}{% endblock %}

    {% block desc %}
    <h4 class="desc">Simple file transfer.</h4>
    {% endblock %}

    <hr> 
    {% block content %} {% endblock %}
    <footer id="footer">
        {% block footer %} 
        <p class="warning">By using this site, you agree to not uploading illegal content</p>
        {% endblock %}
    </footer>
    {% block js %} {% endblock %}
    
    <noscript><img src="https://shynet.angm.xyz/ingress/f6f73ec5-9ed0-412b-a777-27a53a304367/pixel.gif"></noscript>
    <script defer src="https://shynet.angm.xyz/ingress/f6f73ec5-9ed0-412b-a777-27a53a304367/script.js"></script>
</body>

</html>

templates/downloader/deleted.html
{% extends "base.html" %} 
{% block title %}ZeroFile - Gone!{% endblock %} 
{% block content %}
    <span>410: This file has expired or was deleted! It is no longer available.</span>
{% endblock %}

templates/manager/files.html
{% extends "base.html" %} 
{% load static %}

{% block title %}ZeroFile - My Files{% endblock %} 
{% block css %}<link rel="stylesheet" href="{% static 'css/files.css' %}">{% endblock %}

{% block headerlink %}<a href="{% url 'uploader:upload' %}" class="link">Home</a>{% endblock %}

{% block content %}
    <div class="files">
        <table width="90%">
            <tr>
                <th>Name</th>
                <th>Upload Date</th>
                <th>Expire Date</th>
                <th>Expired?</th>
            </tr>

            {% for f in files %}
            {% if f.deleted %}<tr class="expired">{% else %}<tr>{% endif %}
                <td>
                    <a href="/{{ f.fid }}">{{ f.name }}</a>
                </td>
                <td>{{ f.date }}</td>
                <td>{{ f.expiry }}</td>
                {% if f.deleted %}<td>Yes</td>
                {% else %}<td>No</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/manager/register.html
{% extends "base.html" %} 
{% load static %}

{% block title %}ZeroFile - Register{% endblock %} 
{% block css %}<link rel="stylesheet" href="{% static 'css/register.css' %}">{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %} {{ form }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

templates/streamer/index.html
{% extends "base.html" %} 
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/streamer.css' %}">{% endblock %}

{% block mode %}
<a class="mode" href="{% url 'uploader:upload' %}">switch to host mode</a>
{% endblock %}

{% block desc %}<h4 class="desc">Simple p2p file streaming.</h4>{% endblock %}

{% block content %}
    <main>
    {% if host %}
        <div id="before-connection">
            <p>Your Stream ID: <span id="stream-id">......</span></p>
            <a onclick="copyURL();">
                <!-- Rather ugly hack to get the text to stay centered... -->
                <span class="hidden">Copied!</span> 
                <span class="copy-link">Click here to copy a link for the receiver to the clipboard.</span>
                <span id="clipboard-copied">Copied!</span>
            </a>
            <p>Waiting for connection...</p>
        </div>

        <div class="nodisplay" id="connected">
            <p>Connection established!</p>

            <div class="file-div">
                <label class="fileinput">
                    <p id="filetext">Select or drop file(s) to stream...</p>
                    <input id="fileselect" type="file" name="fileselect" onchange="updateFile();">
                </label>
            </div>

            <button class="upload-button" id="upload-button" onclick="sendFile();">Send</button>

            <p>Currently uploading: <span id="current">None</span></p>
            <div id="meter" class="meter"><span style="width: 0%"></span></div>
        </div>
    {% else %}
        <p id="connecting-msg">Connecting to {{ stream_id }}...</p>
        <div id="meter" class="meter hidden"><span style="width: 0%"></span></div>
    {% endif %}
    </main>
{% endblock %}

{% block js %}
    <script src="https://unpkg.com/peerjs@1.3.1/dist/peerjs.min.js"></script>
    <script src="{% static 'js/streamer.js' %}"></script>
{% endblock %}

templates/uploader/ajax.html
<p class="linktext">"{{ file_name }}" uploaded! Link:
    <a class="link" href="{% url 'downloader:download' file_id %}">{% url 'downloader:download' file_id %}</a>
</p>

templates/uploader/index.html
{% extends "base.html" %} 
{% load static %}

{% block mode %}
<a class="mode" href="{% url 'streamer:stream' %}">switch to stream mode</a>
{% endblock %}

{% block content %}
    <form enctype="multipart/form-data" action="/" method="post" id="upload-form" onsubmit="return validateFile();">
        {% csrf_token %}
        <div class="file-div">
            <label class="fileinput">
                <p id="filetext">Select or drop file...</p>
                <input id="fileselect" type="file" name="fileselect" onchange="updateFile();">
            </label>
        </div>

        <div class="timeout-div" title="The file will be deleted after this time and won't be downloadable anymore.">
            <label class="timeout-label" for="timeout">Expires in 1</label>
            <select id="timeout" class="timeout">
                <option value="minute" selected>minute</option>
                <option value="hour">hour</option>
                <option value="day">day</option>
                <option value="week">week</option>
            </select>
        </div>

        <input type="submit" value="Upload" class="upload-button" id="upload-button">
    </form>
{% endblock %}

{% block footer %}
    {% if file_id %}
    <p class="linktext">"{{ file_name }}" uploaded! Link:
        <a class="link" href="{% url 'downloader:download' file_id %}">{% url 'downloader:download' file_id %}</a>
    </p>
    {% elif file_toobig %}
    <p>File too big! Only files >50MB are allowed.</p>
    {% else %}
    <p class="warning">By using this site, you agree to not uploading illegal content</p>
    {% endif %}
{% endblock %}

{% block js %}<script src="{% static 'js/index.js' %}"></script>{% endblock %}

templates/uploader/invalid_timeout.html
<p class="linktext">
    Unknown timeout (are you doing raw requests?)
</p>

templates/uploader/not_allowed_mime.html
<p class="linktext">
    You may not anonymously upload HTML or PHP files. (Thank people like AsnanGans, Sa$k66 and CyberNob spamming scammy "You are hacked" pages.)
</p>